# Generated by Django 4.1.3 on 2022-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcomment',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст'),
        ),
    ]
